apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: fcbksv10/customer:latest
        ports:
        - containerPort: 8080
        env:
          - name: ORDER_SVC_URL
            value: "http://order-service.default.svc.cluster.local:9090"

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
