openapi: 3.0.3
info:
  title: Customer Service
  description: |-
    Simple microserivce that exposes Customer API's
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost:8080
tags:
  - name: customer
    description: Customer API's
paths:
  /customer/{id}:
    get:
      tags:
        - customer
      summary: Get Customer by id
      description: Get Customer by id
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          description: Customer ID
          required: true
          schema:
            type: string
            default: 1ddd9bf7-014a-44e2-a377-f1937782e1e6
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    
  /customer:
    get:
      tags:
        - customer
      summary: Get All Customers
      operationId: getAllCustomers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    
    post:
      tags:
        - customer
      summary: Save Customer
      operationId: saveCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomerResponse'
                  
  
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
          example: 1ddd9bf7-014a-44e2-a377-f1937782e1e6
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        age:
          type: integer
          example: 20
        addressLine1:
          type: string
          example: "1, Cross Street"
        addressLine2:
          type: string
          example: "Dallas, Texas"
        order:
          type: object
          properties:
            id:
              type: integer
              example: 1
            items:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: "Mac Studio"
                  price:
                    type: number
                    example: 2000.00
                
    CreateCustomerRequest:
      type: object
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        age:
          type: integer
          example: 20
        addressLine1:
          type: string
          example: "1, Cross Street"
        addressLine2:
          type: string
          example: "Dallas, Texas"
                
    CreateCustomerResponse:
      type: object
      properties:
        id:
          type: string
          example: 1ddd9bf7-014a-44e2-a377-f1937782e1e6
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        age:
          type: integer
          example: 20
        addressLine1:
          type: string
          example: "1, Cross Street"
        addressLine2:
          type: string
          example: "Dallas, Texas"
